### PR TITLE
Allow nested object properties to be indexed

### PR DESCRIPTION
**Pull request by konradjurk**
I couldn't find an API which allows to index nested object property values, so I tweaked the value lookup a bit so that `search.addIndex('nested.property')` is able to index a nested property:

```
{
  nested: {
    property: 'value'
  }
}
```

If a property name is passed to `addIndex()` which does not look like a path (contains no `.`), the original brackets implementation is used (`document[propertyName]`). Also, if one of the intermediate objects of a path does not exist, we'll fallback to the brackets implementation, too. Just in case someone has an object looking like this:

```
{
  'not.nested': 'value'
}
```

Added tests for that.

### CODE REVIEW

**Comment by bvaughn** [comment]
Again, thanks for the contribution! :)

I like the ability to search nested fields but I'm not digging the ambiguity between `object['a.b.c.']` and `object.a.b.c`.

What do you think about either adding a new method (eg `addNestedIndex(fields: Array<string>)`) or updating `addIndex` to accept either a string or an array-of-strings. Then it's explicit.

**Comment by konradjurk** [comment]
Much better! What would you go for? New method or 'overloaded' `addIndex()`?

**Comment by bvaughn** [comment]
As the first user of this feature, I'd say.. take your pick :) Honestly either one is fine. TypeScript supports unions so we could overload if needed.

I have the _tiniest_ preference for a new method.

**Comment by konradjurk** [comment]
I had the same preference, but I ended up with two methods doing exactly the same so I decided to make `addIndex()` accept a string and and array of strings. People who need this feature _will_ have a look into the docs 💯  :)

**Comment by bvaughn** [comment]
1.3.0 release just went out with your changes. Gave you a shout-out in the changelog and tag.

Thanks again for the contributions, @konradjurk  :)

**Comment by konradjurk** [comment]
Nice, thanks @bvaughn :)

**Pull request merged**
